services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: MONGODB_URI
        sync: false
